@startuml
left to right direction

actor :Perito: as Perito
actor :Coordinador General: as Coordinador

package "3. Operativa de Pedidos de Extracción" {
    
    package "Gestión de Causas Judiciales" as P3.1 {
    }
    
    package "Gestión de Oficios" as P3.2 {
   
    }
    
    package "Gestión de Aperturas" as P3.3{
    }
    
}

Perito --> P3.1
Coordinador --> P3.1

Perito --> P3.2
Coordinador --> P3.2 

Perito --> P3.3
Coordinador --> P3.3
@endum