@startuml
left to right direction

actor :Perito: as Perito
actor :Coordinador General: as Coordinador

package "3. Operativa de Pedidos de Extracción" {
    
    package "Gestión de Causas Judiciales" {
        usecase "CU-3.01.01: Registrar Nueva Causa Judicial" as CU_3_01_01 <<process>>
        usecase "CU-3.01.02: Modificar Datos de Causa Judicial" as CU_3_01_02 <<process>>
        usecase "CU-3.01.03: Consultar Detalle de Causa Judicial" as CU_3_01_03 <<navigation>>
        usecase "CU-3.01.04: Listar Causas Judiciales" as CU_3_01_04 <<navigation>>
        usecase "CU-3.01.05: Deshabilitar Causa Judicial" as CU_3_01_05 <<process>>
    }
    
    package "Gestión de Oficios" {
        usecase "CU-3.02.01: Registrar Nuevo Oficio" as CU_3_02_01 <<process>>
        usecase "CU-3.02.02: Modificar Oficio" as CU_3_02_02 <<process>>
        usecase "CU-3.02.03: Deshabilitar Oficio" as CU_3_02_03 <<process>>
        usecase "CU-3.02.04: Consultar Detalle de Oficio" as CU_3_02_04 <<navigation>>
    }
    
    package "Gestión de Aperturas" {
        usecase "CU-3.03.01: Registrar nueva apertura" as CU_3_03_01 <<process>>
        usecase "CU-3.03.02: Modificar apertura" as CU_3_03_02 <<process>>
        usecase "CU-3.03.03: Deshabilitar apertura" as CU_3_03_03 <<process>>
        usecase "CU-3.03.04: Consultar apertura" as CU_3_03_04 <<navigation>>
    }
    
    CU_3_02_01 <.. CU_3_03_01 : <<extend>>
}

Perito --> CU_3_01_01
Perito --> CU_3_01_02
Perito --> CU_3_01_03
Perito --> CU_3_01_04
Perito --> CU_3_01_05

Perito --> CU_3_02_01
Perito --> CU_3_02_02
Perito --> CU_3_02_03
Perito --> CU_3_02_04

Perito --> CU_3_03_01
Perito --> CU_3_03_02
Perito --> CU_3_03_03
Perito --> CU_3_03_04

Coordinador --> CU_3_01_03
Coordinador --> CU_3_01_04
Coordinador --> CU_3_02_04
Coordinador --> CU_3_03_04
@endum