@startuml
left to right direction

actor :Perito: as Perito

package "4. Gestión de Dispositivos de Evidencia" {
    usecase "CU-4.01: Registrar Dispositivo" as CU_4_01
    usecase "CU-4.03: Consultar Detalle de Dispositivo\n«navigation»" as CU_4_03
    usecase "CU-4.04: Actualizar Ubicación Física" as CU_4_04
    usecase "CU-4.05: Cargar Fotografías de Evidencia" as CU_4_05
    usecase "CU-4.06: Registrar Observación Técnica \n en Bitacora de Dispositivo" as CU_4_06
}

Perito --> CU_4_01
Perito --> CU_4_03
Perito --> CU_4_04
Perito --> CU_4_05
Perito --> CU_4_06
@endum