@startuml
left to right direction

actor :Coordinador General: as Coordinador
actor :Perito: as Perito

package "6 & 7. Consultas, Reportes y Supervisión" {
    usecase "CU-6.01: Visualizar Dashboard Global" as CU_6_01
    usecase "CU-6.04: Consultar Causa de Perito" as CU_6_04
    usecase "CU-7.01: Generar Resumen Técnico\n(para Informe)" as CU_7_01
    usecase "CU-7.04: Descargar Reporte Estadístico" as CU_7_04
}

Perito --> CU_7_01

Coordinador --> CU_6_01
Coordinador --> CU_6_04
Coordinador --> CU_7_04
@endum