@startuml
!theme plain
left to right direction

actor "Administrador" as Admin
actor "Coordinador General" as Coordinador

frame "ForenSys" {

    package "Gestión de Catálogos\n(ABM para datos parametrizados)" as P2

    package "Gestión de Acceso y Perfil" as P1

    package "Trazabilidad y Cadena de Custodia" as P5

    package "Operativa de Pedidos de Extracción" as P3

    package "Gestión de Dispositivos de Evidencia" as P4

    package "Reportes y Supervisión\n(Coordinador General)" as P6
}

actor "Perito" as Perito

P6 -[hidden]-> Perito

Admin --> P1
Admin --> P2
Admin --> P5

Coordinador --> P1
Coordinador --> P3
Coordinador --> P4
Coordinador --> P5
Coordinador --> P6

P1 <-- Perito
P3 <-- Perito
P4 <-- Perito
P5 <-- Perito
P6 <-- Perito

@enduml